# Generated by Django 4.2.7 on 2023-12-06 23:19

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('idUsuario', models.AutoField(db_column='idUsuario', primary_key=True, serialize=False)),
                ('nombreUsuario', models.CharField(db_column='nombreUsuario', max_length=50)),
                ('apellidoPaterno', models.TextField(db_column='apellidoPaterno', max_length=50)),
                ('apellidoMaterno', models.TextField(db_column='apellidoMaterno', max_length=50)),
                ('password', models.TextField(max_length=128)),
                ('correoElectronico', models.EmailField(db_column='correoElectronico', max_length=254, unique=True)),
                ('numeroTelefonico', models.IntegerField(db_column='numeroTelefonico')),
                ('groups', models.ManyToManyField(blank=True, related_name='usuarios', to='auth.group', verbose_name='Grupos')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='usuarios', to='auth.permission', verbose_name='Permisos')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.AutoField(db_column='idCategoria', primary_key=True, serialize=False)),
                ('nombreCategoria', models.TextField(db_column='nombreCategoria', max_length=50)),
            ],
            options={
                'db_table': 'Categoria',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('idColor', models.AutoField(db_column='idColor', primary_key=True, serialize=False)),
                ('nombreColor', models.TextField(db_column='nombreColor', max_length=30)),
            ],
            options={
                'db_table': 'Color',
            },
        ),
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id_Formulario', models.AutoField(db_column='id_Formulario', primary_key=True, serialize=False)),
                ('pregunta1', models.TextField(db_column='¿Qué busca en una tienda online?')),
                ('pregunta2', models.TextField(db_column='¿Qué forma de pago desea tener en una tienda online?')),
                ('pregunta3', models.TextField(db_column='¿En que dispositivos visita mas una tienda online?')),
                ('pregunta4', models.TextField(db_column='En una tienda online de calzado, ¿Qué tipo de calzado busca con mas frecuencia?')),
                ('pregunta5', models.TextField(db_column='¿Qué métodos de búsqueda prefiere para un tienda de calzado online? ')),
                ('pregunta6', models.TextField(db_column='¿Se basa de las opiniones y calificaciones de los demás para definir si comprar o no un producto online?')),
                ('pregunta7', models.TextField(db_column='¿Cómo prefieres la vista de productos online?')),
                ('pregunta8', models.TextField(db_column='¿Qué le gustaría tener por el uso y compra de productos online?')),
                ('pregunta9', models.TextField(db_column='¿Te gustaría recibir notificaciones o avisos sobre ofertas y promociones? ')),
                ('pregunta10', models.TextField(db_column='¿Qué método de registro prefieres en tiendas online?')),
            ],
            options={
                'db_table': 'Formulario',
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('idMarca', models.AutoField(db_column='idMarca', primary_key=True, serialize=False)),
                ('nombreMarca', models.TextField(db_column='nombreMarca', max_length=20)),
                ('descripcion', models.TextField(db_column='descripcion', max_length=150)),
            ],
            options={
                'db_table': 'Marcas',
            },
        ),
        migrations.CreateModel(
            name='Talla',
            fields=[
                ('idTalla', models.AutoField(db_column='idTalla', primary_key=True, serialize=False)),
                ('nombreTalla', models.FloatField(db_column='nombreTalla')),
            ],
            options={
                'db_table': 'Talla',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.AutoField(db_column='idProducto', primary_key=True, serialize=False)),
                ('nombreProducto', models.TextField(db_column='nombreProducto', max_length=50)),
                ('descripcionProducto', models.TextField(db_column='descripcionProducto', max_length=100)),
                ('precioProducto', models.FloatField(db_column='precioProducto')),
                ('linkStripe', models.TextField(db_column='linkStripe', max_length=100)),
                ('imagen', models.ImageField(upload_to='imagenes/')),
                ('fk_categoria', models.ForeignKey(db_column='fk_categoria', on_delete=django.db.models.deletion.CASCADE, to='api.categoria')),
                ('fk_color', models.ForeignKey(db_column='fk_color', on_delete=django.db.models.deletion.CASCADE, to='api.color')),
                ('fk_marca', models.ForeignKey(db_column='fk_marca', on_delete=django.db.models.deletion.CASCADE, to='api.marca')),
                ('fk_talla', models.ForeignKey(db_column='fk_talla', on_delete=django.db.models.deletion.CASCADE, to='api.talla')),
            ],
            options={
                'db_table': 'Producto',
            },
        ),
        migrations.CreateModel(
            name='CarroCompra',
            fields=[
                ('idCarroCompras', models.AutoField(db_column='idCarroCompras', primary_key=True, serialize=False)),
                ('fk_producto', models.ForeignKey(db_column='fk_producto', on_delete=django.db.models.deletion.CASCADE, to='api.producto')),
                ('fk_usuario', models.ForeignKey(db_column='fk_usuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'CarroCompra',
            },
        ),
    ]
