# Generated by Django 4.2.7 on 2024-01-05 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_marca_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='fk_categoria',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
