# Generated by Django 4.2.7 on 2024-01-10 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_producto_fk_categoria_delete_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='descripcionProducto',
            field=models.TextField(db_column='descripcionProducto', max_length=1000),
        ),
    ]
